
name: release
run-name: Release ${{ github.event.repository.name }} ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version number (e.g. 1.0.2)"
        required: true
        type: string
  # When calling this workflow from another repo, ensure the following files are
  # located in the local .github/workflow-resources directory:
  #   • release-pr-body.md
  #   • release-version-check.sh
  workflow_call:
    inputs:
      version:
        description: "Release version number (e.g. 1.0.2)"
        required: true
        type: string

jobs:
  revdep-check:
    uses: r-devel/recheck/.github/workflows/recheck.yml@v1
    with:
      which: most

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version number
        env:
          INPUT_VERSION: ${{ inputs.version }}
        run: .github/workflow-resources/release-version-check.sh

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::rhub

      - name: Update DESCRIPTION version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          desc::desc_set_version(Sys.getenv("VERSION"))
        shell: Rscript {0}

      - name: Update NEWS.md version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "[unreleased]"
          replace: "${{ github.event.repository.name }} ${{ inputs.version }}"
          include: "NEWS.md"
          regex: false

      - name: Import GPG signing key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Render PR body
        id: pr-body
        uses: chuhlomin/render-template@v1
        with:
          template: .github/workflow-resources/release-pr-body.md
          vars: |
            version: ${{ inputs.version }}
            artifacts_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_PAT }}
          author: ${{ secrets.BOT_USER }}
          committer: ${{ secrets.BOT_USER }}
          commit-message: "[automated] Prepare for ${{ inputs.version }} release"
          branch: release/${{ inputs.version }}
          title: Release version ${{ inputs.version }}
          body: ${{ steps.pr-body.outputs.result }}
          reviewers: pdil
          assignees: pdil
          labels: release
          delete-branch: true
          draft: true
