
name: Check for new shapefiles

on:
  schedule:
      # runs at midnight on the 1st of March and September
    - cron: '0 0 1 3,9 *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r data-raw/scripts/requirements.txt

      - name: Download shapefiles
        run: |
          python data-raw/scripts/shapefiles.py
          echo "python_exit_code=$?" >> $GITHUB_ENV
        continue-on-error: true

      - name: Send failure notification
        if: ${{ failure() }}
        run: python pushover.py "⚠️ usmapdata updater failed to find new shapefiles." "LOW"
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2 

      - name: Setup usmapdata
        if: ${{ success() }}
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Modify shapefiles
        if: ${{ success() }}
        env:
          STATE_SHP_DIR: "data-raw/scripts/shapefiles/$state_shp_path"
          COUNTY_SHP_DIR: "data-raw/scripts/shapefiles/$county_shp_path"
          STATE_OUTPUT: "inst/extdata/us_states.gpkg"
          COUNTY_OUTPUT: "inst/extdata/us_counties.gpkg"
        run: |
          Rscript -e "usmapdata:::create_us_map('states', Sys.getenv('STATE_SHP_DIR'), Sys.getenv('STATE_OUTPUT'))"
          Rscript -e "usmapdata:::create_us_map('counties', Sys.getenv('COUNTY_SHP_DIR'), Sys.getenv('COUNTY_OUTPUT'))"

      - name: Determine pull request parameters
        if: ${{ success() }}
        run: |
          echo "branch_name=data-update/$(date +'%B-%Y')" >> "$GITHUB_ENV"
          echo "pr_title=Update map data - $(date +'%B %Y')" >> "$GITHUB_ENV"

      - name: Open pull request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update map data based on latest shapefiles
          branch: ${{ env.branch_name }}
          title: ${{ env.pr_title }}
          body: |
            Updated map data based on latest shapefiles from
            the US Census Bureau's [cartographic boundary files][1].

            ### Review Checklist
            - [ ] Ensure all checks and tests pass
            - [ ] Load current branch with `devtools::install_github("usmapdata", "${{ env.branch_name }}")` and test `usmap`
            - [ ] Perform smoke test of all plotting features to ensure consistency
            - [ ] Update data file changelog in [`usmap` `README.md`][2]

            [1]: https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html
            [2]: https://github.com/pdil/usmap/blob/master/README.md
          assignees: pdil
          labels: data update
          reviewers: pdil
          delete-branch: true

      - name: Send success notification
        if: ${{ success() }}
        run: python pushover.py "✅ usmapdata has updated its data files, a PR review is needed."
